List<Map<String, dynamic>> dummyCoffee = [
  {'image': 'assets/coffee/img1.png', 'name': '아메리카노', 'price': 3000},
  {'image': 'assets/coffee/img2.png', 'name': '에스프레소', 'price': 3500},
  {'image': 'assets/coffee/img3.png', 'name': '카푸치노', 'price': 4000},
  {'image': 'assets/coffee/img4.png', 'name': '카페라떼', 'price': 4200},
  {'image': 'assets/coffee/img5.png', 'name': '카페모카', 'price': 4300},
  {'image': 'assets/coffee/img6.png', 'name': '캐러멜마키아또', 'price': 4500},
  {'image': 'assets/coffee/img7.png', 'name': '바닐라라떼', 'price': 4600},
  {'image': 'assets/coffee/img8.png', 'name': '고구마라떼', 'price': 4800},
  {'image': 'assets/coffee/img9.png', 'name': '흑임자라떼', 'price': 5000},
  {'image': 'assets/coffee/img1.png', 'name': '콜드블루', 'price': 5500},
  {'image': 'assets/coffee/img11.png', 'name': '레몬에이드', 'price': 3200},
  {'image': 'assets/coffee/img12.png', 'name': '오렌지주스', 'price': 3500},
  {'image': 'assets/coffee/img13.png', 'name': '딸기라떼', 'price': 3800},
  {'image': 'assets/coffee/img14.png', 'name': '초콜릿라떼', 'price': 3500},
  {'image': 'assets/coffee/img15.png', 'name': '그린티라떼', 'price': 4500},
  {'image': 'assets/coffee/img16.png', 'name': '밀크티', 'price': 4300},
  {'image': 'assets/coffee/img17.png', 'name': '아이스티', 'price': 2800},
  {'image': 'assets/coffee/img18.png', 'name': '스무디', 'price': 4000},
  {'image': 'assets/coffee/img19.png', 'name': '프라푸치노', 'price': 4200},
  {'image': 'assets/coffee/img1.png', 'name': '디카페인아메리카노', 'price': 5600},
];

List<Map<String, dynamic>> dummyCake = [
  {'image': 'assets/cake/img1.png', 'name': '딸기 케이크', 'price': 3200},
  {'image': 'assets/cake/img2.png', 'name': '초코 케이크', 'price': 3000},
  {'image': 'assets/cake/img3.png', 'name': '레드벨벳 케이크', 'price': 3300},
  {'image': 'assets/cake/img4.png', 'name': '치즈 케이크', 'price': 4000},
  {'image': 'assets/cake/img5.png', 'name': '티라미수 케이크', 'price': 3500},
  {'image': 'assets/cake/img6.png', 'name': '당근 케이크', 'price': 3800},
  {'image': 'assets/cake/img7.png', 'name': '무스 케이크', 'price': 4200},
  {'image': 'assets/cake/img8.png', 'name': '오페라 케이크', 'price': 4800},
  {'image': 'assets/cake/img9.png', 'name': '몽블랑 케이크', 'price': 4500},
  {'image': 'assets/cake/img10.png', 'name': '롤 케이크', 'price': 2000},
];
